import type { Metadata } from "next";
import "./globals.css";
import Container from "@/components/container";
import ThemeProvider from "@/components/theme-provider";
import { Karla } from "next/font/google";
import Header from "@/components/header";

const karla = Karla({
  subsets: ["latin"],
  preload: true,
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Akmal Dira - Personal Website",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${karla.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Container className="flex flex-col items-start md:flex-row gap-6">
            <Header />
            <main className="w-full overflow-x-hidden pt-20 md:pt-4">
              {children}
            </main>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
